---
  - name: Check if Jenkins JNLP agent variables are defined
    assert:
      that:
        - "jenkins_master is defined"
        - "jenkins_agent_secret is defined"
    tags:
      - jenkins-agent
  - name: Make Jenkins JNLP agent directories
    become: yes
    become_method: sudo
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ jenkins_agent_user }}"
      group: "{{ jenkins_agent_group }}"
    with_items:
      - "{{ jenkins_agent_home }}"
      - "{{ jenkins_agent_root }}/bin"
    tags:
      - jenkins-agent
  - name: Template Jenkins JNLP agent files
    become: yes
    become_method: sudo
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: jenkins-agent.service, dest: /etc/systemd/system/jenkins-agent.service, mode: 755 }
      - { src: jenkins-agent.default, dest: /etc/default/jenkins-agent, mode: 644 }
    notify: Start Jenkins JNLP agent
    tags: jenkins-agent
