---
  - name: Start Jenkins JNLP agent
    become: yes
    become_method: sudo
    systemd:
      name: jenkins-agent
      enabled: yes
      state: restarted
      daemon_reload: yes
    tags:
      - jenkins-agent